paths:
  data: "data/housing.csv"
  model: "models/model.pkl"
  reports: "reports/"

split:
  test_size: 0.2
  random_state: 42

target: "median_house_value"

numerical:
  - longitude
  - latitude
  - housing_median_age
  - total_rooms
  - total_bedrooms
  - population
  - households
  - median_income

categorical:
  - ocean_proximity